baseURL = "https://roryamos.github.io/blog/"
languageCode = "zh-tw"
title = "Rory Blog"
theme = "maupassant"
publishDir = "docs"

# SES friendly url:s
canonifyurls = true

# Pagination
paginate = 10
paginatePath = "page"

preserveTaxonomyNames = true

[permalinks]
    post = "/:year/:month/:day/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
                               category = "categories"

[author]
    name = "Rory"

[params]
    author = "Rory"
    subtitle = "專注於Linux, CI/CD, Golang, Lean and Agile"
    keywords = "php,golang,nodejs,murmur,小程序"
    description = "從事程式設計工作近二十年, 陸續學習過PHP, .Net, Java, NodeJs, Go. 從 Web 到移動端再到目前專注的服務器端."
    busuanzi = true

[params.utteranc]
    enable = true
    repo = "roryamos/blog"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]

    [[menu.main]]
        identifier = "archives"
        name = "歸檔"
        url = "archives/"
        weight = 3

    [[menu.main]]
        identifier = "about"
        name = "關於"
        url = "about/"
        weight = 4

[[params.links]]
    title = "飞雪无情的博客"
    name = "飞雪无情的博客"
    url = "https://www.flysnow.org"

[[params.links]]
    title = "旅人的部落格"
    name = "旅人的部落格"
    url = "http://blog.udn.com/tripc/article"

