baseURL = "https://twrory.com/"
languageCode = "zh-tw"
title = "Rory Blog"
theme = "maupassant"
publishDir = "docs"

# SES friendly url:s
canonifyurls = true

# Pagination
[pagination]
pagerSize = 10
path = "page"

preserveTaxonomyNames = true
# googleAnalytics = "G-LNYLGP6FL5"

[permalinks]
    post = "/:year/:month/:day/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    author = "Rory"
    subtitle = "專注於Linux, Docker, CI/CD, Golang, Lean and Agile"
    keywords = "linux,docker,ci,cd,php,go,golang,nodejs,lean,agile,murmur,小程序"
    description = "從事程式設計工作近二十年, 陸續學習過PHP, .Net, Java, NodeJs, Go. 從 Web 到移動端再到目前專注的服務器端."
    busuanzi = true
    # Google Ads
    googleAd = "ca-pub-9397388882562141"
    googleAnalytics = "G-LNYLGP6FL5"

[params.utteranc]
    enable = true
    repo = "roryamos/blog"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]

    [[menu.main]]
        identifier = "archives"
        name = "歸檔"
        url = "archives/"
        weight = 3

    [[menu.main]]
        identifier = "about"
        name = "關於"
        url = "about/"
        weight = 4

[[params.links]]
    title = "飞雪无情的博客"
    name = "飞雪无情的博客"
    url = "https://www.flysnow.org"

[[params.links]]
    title = "旅人的部落格"
    name = "旅人的部落格"
    url = "http://blog.udn.com/tripc/article"

